#!/usr/bin/env python3
"""Generate Rust constants for the triality transport study."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
from typing import Any


def parse_arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--triality",
        type=Path,
        default=Path("artifacts/exact/triality44.json"),
    )
    parser.add_argument(
        "--split",
        type=Path,
        default=Path("artifacts/exact/split-octonion.json"),
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("studies/triality_transport/src/generated.rs"),
    )
    return parser.parse_args()


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as source:
        while chunk := source.read(1024 * 1024):
            digest.update(chunk)
    return digest.hexdigest()


def dimensions(value: Any) -> list[int]:
    result: list[int] = []
    while isinstance(value, list):
        result.append(len(value))
        value = value[0] if value else None
    return result


def rational_literal(value: list[int]) -> str:
    numerator, denominator = value
    if denominator <= 0:
        raise ValueError(f"Invalid denominator: {value}")
    if denominator == 1:
        return f"{numerator}.0"
    return f"({numerator}.0 / {denominator}.0)"


def integer_literal(value: int) -> str:
    return f"{value}.0"


def render_array(value: Any, scalar_renderer: Any, indent: int = 0) -> str:
    if not isinstance(value, list):
        return scalar_renderer(value)
    if not value:
        return "[]"
    prefix = " " * indent
    child_prefix = " " * (indent + 4)
    rendered = [render_array(item, scalar_renderer, indent + 4) for item in value]
    return "[\n" + "".join(f"{child_prefix}{item},\n" for item in rendered) + f"{prefix}]"


def render_rational_array(value: Any, indent: int = 0) -> str:
    if (
        isinstance(value, list)
        and len(value) == 2
        and all(isinstance(item, int) for item in value)
    ):
        return rational_literal(value)
    if not isinstance(value, list):
        raise TypeError(f"Unexpected rational array value: {value!r}")
    prefix = " " * indent
    child_prefix = " " * (indent + 4)
    rendered = [render_rational_array(item, indent + 4) for item in value]
    return "[\n" + "".join(f"{child_prefix}{item},\n" for item in rendered) + f"{prefix}]"


def main() -> int:
    arguments = parse_arguments()
    triality_path = arguments.triality.resolve()
    split_path = arguments.split.resolve()
    output_path = arguments.output.resolve()
    triality = json.loads(triality_path.read_text(encoding="utf-8"))
    split = json.loads(split_path.read_text(encoding="utf-8"))

    representations = triality["representationsRationals"]
    pairs = triality["liePairsZeroBased"]
    para_tensor = split["paraMultiplicationTensor"]
    metric_diagonal = [split["metric"][index][index] for index in range(8)]
    expected_dimensions = {
        "representations": [3, 28, 8, 8, 2],
        "pairs": [28, 2],
        "paraTensor": [8, 8, 8],
    }
    actual_dimensions = {
        "representations": dimensions(representations),
        "pairs": dimensions(pairs),
        "paraTensor": dimensions(para_tensor),
    }
    if actual_dimensions != expected_dimensions:
        raise ValueError(
            f"Fixture dimensions changed: expected {expected_dimensions}, "
            f"found {actual_dimensions}"
        )

    denominators = sorted(
        {
            scalar[1]
            for representation in representations
            for generator in representation
            for row in generator
            for scalar in row
        }
    )
    if any(denominator <= 0 for denominator in denominators):
        raise ValueError(f"Invalid representation denominators: {denominators}")

    content = "\n".join(
        [
            "// Generated by scripts/generate_triality_transport_constants.py.",
            "// Do not edit by hand.",
            "",
            "#[rustfmt::skip]",
            f'pub const TRIALITY_FIXTURE_SHA256: &str = "{sha256_file(triality_path)}";',
            "#[rustfmt::skip]",
            f'pub const SPLIT_FIXTURE_SHA256: &str = "{sha256_file(split_path)}";',
            "pub const STATE_DIMENSION: usize = 24;",
            "pub const MODULE_DIMENSION: usize = 8;",
            "pub const LIE_DIMENSION: usize = 28;",
            "",
            "#[rustfmt::skip]",
            "pub const LIE_PAIRS: [[usize; 2]; LIE_DIMENSION] = "
            + render_array(pairs, str)
            + ";",
            "",
            "#[rustfmt::skip]",
            "pub const METRIC_DIAGONAL: [f64; MODULE_DIMENSION] = "
            + render_array(metric_diagonal, integer_literal)
            + ";",
            "",
            "#[rustfmt::skip]",
            "pub const PARA_TENSOR: [[[f64; MODULE_DIMENSION]; MODULE_DIMENSION]; MODULE_DIMENSION] = "
            + render_array(para_tensor, integer_literal)
            + ";",
            "",
            "#[rustfmt::skip]",
            "pub static REPRESENTATIONS: [[[[f64; MODULE_DIMENSION]; MODULE_DIMENSION]; LIE_DIMENSION]; 3] = "
            + render_rational_array(representations)
            + ";",
            "",
        ]
    )
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8", newline="\n")
    print(f"triality_sha256={sha256_file(triality_path)}")
    print(f"split_sha256={sha256_file(split_path)}")
    print(f"representation_denominators={denominators}")
    print(f"output={output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())