#!/usr/bin/env python3
"""Generate invariant matrices for the curved Einstein-spinor study."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path


SPINOR_DIMENSION = 16


def parse_arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--clifford-fixture",
        type=Path,
        default=Path("artifacts/exact/cl44-seed.json"),
    )
    parser.add_argument(
        "--geometry-fixture",
        type=Path,
        default=Path("artifacts/curved-spin-geometry/geometry.json"),
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("studies/einstein_spinor_44/src/generated.rs"),
    )
    return parser.parse_args()


def sha256_file(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def transpose(matrix: list[list[int]]) -> list[list[int]]:
    return [list(column) for column in zip(*matrix, strict=True)]


def multiply(left: list[list[int]], right: list[list[int]]) -> list[list[int]]:
    columns = transpose(right)
    return [
        [sum(a * b for a, b in zip(row, column, strict=True)) for column in columns]
        for row in left
    ]


def identity(dimension: int) -> list[list[int]]:
    return [
        [int(row == column) for column in range(dimension)]
        for row in range(dimension)
    ]


def render_array(value: object, indent: int = 0) -> str:
    if isinstance(value, int):
        return f"{value}.0"
    if not isinstance(value, list):
        raise TypeError(f"Unexpected fixture value: {value!r}")
    prefix = " " * indent
    child_prefix = " " * (indent + 4)
    rendered = [render_array(item, indent + 4) for item in value]
    return "[\n" + "".join(
        f"{child_prefix}{item},\n" for item in rendered
    ) + f"{prefix}]"


def main() -> int:
    arguments = parse_arguments()
    clifford_path = arguments.clifford_fixture.resolve()
    geometry_path = arguments.geometry_fixture.resolve()
    output_path = arguments.output.resolve()
    clifford = json.loads(clifford_path.read_text(encoding="utf-8"))
    geometry = json.loads(geometry_path.read_text(encoding="utf-8"))
    generators: list[list[list[int]]] = clifford["generators"]
    charge: list[list[int]] = identity(SPINOR_DIMENSION)
    for generator in generators[:4]:
        charge = multiply(charge, generator)
    time_gamma = generators[4]
    negative_identity = [
        [-value for value in row] for row in identity(SPINOR_DIMENSION)
    ]
    if charge != transpose(charge):
        raise ValueError("spinor bilinear is not symmetric")
    if multiply(charge, charge) != identity(SPINOR_DIMENSION):
        raise ValueError("spinor bilinear is not an involution")
    if multiply(time_gamma, time_gamma) != negative_identity:
        raise ValueError("time gamma does not square to minus identity")
    if multiply(transpose(time_gamma), charge) != [
        [-value for value in row] for row in multiply(charge, time_gamma)
    ]:
        raise ValueError("time gamma is not skew-adjoint for the bilinear")
    if geometry["spinorBilinear"]["matrix"] != charge:
        raise ValueError("geometry and Clifford spinor bilinears disagree")

    clifford_hash = sha256_file(clifford_path)
    geometry_hash = sha256_file(geometry_path)
    content = "\n".join(
        [
            "// Generated by scripts/generate_einstein_spinor_constants.py.",
            "// Do not edit by hand.",
            "",
            "#[rustfmt::skip]",
            f'pub const CL44_FIXTURE_SHA256: &str = "{clifford_hash}";',
            "#[rustfmt::skip]",
            f'pub const GEOMETRY_FIXTURE_SHA256: &str = "{geometry_hash}";',
            f"pub const SPINOR_DIMENSION: usize = {SPINOR_DIMENSION};",
            "pub const STATE_DIMENSION: usize = 18;",
            "",
            "#[rustfmt::skip]",
            "pub const SPINOR_BILINEAR: [[f64; SPINOR_DIMENSION]; SPINOR_DIMENSION] = "
            + render_array(charge)
            + ";",
            "",
            "#[rustfmt::skip]",
            "pub const TIME_GAMMA: [[f64; SPINOR_DIMENSION]; SPINOR_DIMENSION] = "
            + render_array(time_gamma)
            + ";",
            "",
        ]
    )
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8", newline="\n")
    print(f"cl44_fixture_sha256={clifford_hash}")
    print(f"geometry_fixture_sha256={geometry_hash}")
    print("charge_symmetric=true")
    print("charge_involution=true")
    print("time_gamma_square_minus_identity=true")
    print("time_gamma_charge_skew=true")
    print(f"output={output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
