#!/usr/bin/env python3
"""Generate the real internal-rotation matrix for spinor cosmology."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path


def parse_arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--fixture",
        type=Path,
        default=Path("artifacts/exact/cl44-seed.json"),
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("studies/spinor_cosmology/src/generated.rs"),
    )
    return parser.parse_args()


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as source:
        while chunk := source.read(1024 * 1024):
            digest.update(chunk)
    return digest.hexdigest()


def transpose(matrix: list[list[int]]) -> list[list[int]]:
    return [list(column) for column in zip(*matrix, strict=True)]


def multiply(left: list[list[int]], right: list[list[int]]) -> list[list[int]]:
    columns = transpose(right)
    return [
        [sum(a * b for a, b in zip(row, column, strict=True)) for column in columns]
        for row in left
    ]


def render_array(value: object, indent: int = 0) -> str:
    if isinstance(value, int):
        return f"{value}.0"
    if not isinstance(value, list):
        raise TypeError(f"Unexpected fixture value: {value!r}")
    prefix = " " * indent
    child_prefix = " " * (indent + 4)
    rendered = [render_array(item, indent + 4) for item in value]
    return "[\n" + "".join(f"{child_prefix}{item},\n" for item in rendered) + f"{prefix}]"


def main() -> int:
    arguments = parse_arguments()
    fixture_path = arguments.fixture.resolve()
    output_path = arguments.output.resolve()
    fixture = json.loads(fixture_path.read_text(encoding="utf-8"))
    generators = fixture["generators"]
    if len(generators) != 8 or any(
        len(matrix) != 16 or any(len(row) != 16 for row in matrix)
        for matrix in generators
    ):
        raise ValueError("Clifford fixture generator dimensions changed")
    rotation = generators[4]
    identity = [[int(row == column) for column in range(16)] for row in range(16)]
    if transpose(rotation) != [[-value for value in row] for row in rotation]:
        raise ValueError("selected rotation is not skew")
    if multiply(rotation, rotation) != [[-value for value in row] for row in identity]:
        raise ValueError("selected rotation does not square to minus identity")

    fixture_hash = sha256_file(fixture_path)
    content = "\n".join(
        [
            "// Generated by scripts/generate_spinor_cosmology_constants.py.",
            "// Do not edit by hand.",
            "",
            "#[rustfmt::skip]",
            f'pub const CL44_FIXTURE_SHA256: &str = "{fixture_hash}";',
            "pub const SPINOR_DIMENSION: usize = 16;",
            "pub const STATE_DIMENSION: usize = 18;",
            "",
            "#[rustfmt::skip]",
            "pub const INTERNAL_ROTATION: [[f64; SPINOR_DIMENSION]; SPINOR_DIMENSION] = "
            + render_array(rotation)
            + ";",
            "",
        ]
    )
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8", newline="\n")
    print(f"cl44_fixture_sha256={fixture_hash}")
    print("rotation_skew=true")
    print("rotation_square_minus_identity=true")
    print(f"output={output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())